0.8.1
conda-forge/gwtrigfind-feedstock pull request #2
Opened 2024-07-18 22:34 UTC by eagoetz

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Added package maintainers @areeda and @eagoetz

2024-07-19 00:03 UTC, jakirkham requested changes, later dismissed
CI is not running. Please do not merge until it is resolved

More details in issue: https://github.com/conda-forge/status/issues/184

2024-07-19 03:41 UTC, jakirkham commented
@conda-forge-admin , please restart CI

2024-07-19 20:00 UTC, jakirkham commented
@duncanmmacleod could you please review?

2024-07-21 16:23 UTC, duncanmmacleod approved these changes

2024-07-21 16:23 UTC, merged